# VNPay Sandbox Configuration
vnpay.tmnCode=RWTJ2TDY
vnpay.hashSecret=ZJKTIPJSDNVMBFCEPGKYWKMFXEWBFHND
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/lux_tech/vnpay-return
vnpay.version=2.1.0
vnpay.command=pay